### ISSUE TITLE
Doc2Vec example does not work in TensorFlow r1.10

### ISSUE THREAD

**Issue by rtrevinnoc** [PacktPublishing/TensorFlow-Machine-Learning-Cookbook#7]
After fixing the text_helpers.py file to download the dataset in python3, the next error is...

`Traceback (most recent call last):
  File "doc2vec.py", line 112, in <module>
    final_embed = tf.concat(1, [embed, tf.squeeze(doc_embed)])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 1111, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1027, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1123, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py", line 442, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py", line 353, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
`

Which I managed to fix by updating the parameters in concat from line 112 as specified for tensorflow 1.10, however, the next error I get is...

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1123, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 960, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("nce_loss/Slice_1:0", shape=(250, 300), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "doc2vec.py", line 116, in <module>
    num_sampled, vocabulary_size))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py", line 1246, in nce_loss
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py", line 1074, in _compute_sampled_logits
    sampled_logits = math_ops.matmul(inputs, sampled_w, transpose_b=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py", line 2019, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4499, in mat_mul
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'b' of 'MatMul' Op has type float32 that does not match type int32 of argument 'a'.`

Which can be "fixed" by swapping "final_embed" and "y_target" parameter places in line 115 nce_loss function, however this seems like a really non-functional hack, as the similar words shown by the algorithm are nowhere near correct.

Therefore, I would be glad to get some help here, as a doc2vec implementation on GPU is really needed. Thanks in advance!

**Comment by Xianyong** [comment]
Examples given by this book were developed under on old tensorflow version. You need to upgrade them by yourself.

**Comment by darvid7** [comment]
Quick question re their implementation of doc2vec, does anyone know if it is PV-DM or PV-DBOW?

**Comment by MurtazaTinwala** [comment]
Hi @majomuchi123 

TensorFlow Machine Learning Cookbook - Second Edition is out now. 
Please have a look for all the updated content and codes in the new book on these links: 

Packt website - https://www.packtpub.com/big-data-and-business-intelligence/tensorflow-machine-learning-cookbook-second-edition

Amazon - https://www.amazon.com/dp/1789131685

**Comment by nateraw** [comment]
@darvid7 You've probably figured this out by now, but in case others are wondering, it is PV-DM. You can tell because they are using skipgrams, which is what the PV-DM model is based on.
